use_frameworks!

platform :ios, '8.0'

target 'JKCache_Example' do
  pod 'JKCache', :path => '../'

  target 'JKCache_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
